language: go

go:
- "1.10"

install:
- go get github.com/ghodss/yaml
- go get k8s.io/client-go/tools/clientcmd
- go get k8s.io/client-go/kubernetes
- go get k8s.io/apimachinery/pkg/apis/meta/v1
- go get k8s.io/apimachinery/pkg/types
- go get k8s.io/apimachinery/pkg/util/json

script:
- export GOBIN=${PWD}/bin
- cd src/acl-update
- go install #will it build until I have time to figure out how to write some useful tests for this...